library(rmarkdown)
setwd('~/Dropbox/typ-stats/source')
render("unit1.Rmd", "pdf_document")
render("unit2.Rmd", "pdf_document")
render("unit3.Rmd", "pdf_document")
render("unit4.Rmd", "pdf_document")
render("unit5.Rmd", "pdf_document")
render("unit6.Rmd", "pdf_document")
render("unit7.Rmd", "pdf_document")
render("unit8.Rmd", "pdf_document")
render("unit9.Rmd", "pdf_document")
render("unit10.Rmd", "pdf_document")
