library(rmarkdown)
setwd('~/typ-stats/source')
#render("unit1.Rmd", "html_document")
render("unit2.Rmd", "html_document")
render("unit3.Rmd", "html_document")
render("unit4.Rmd", "html_document")
render("unit5.Rmd", "html_document")
render("unit6.Rmd", "html_document")
render("unit7.Rmd", "html_document")
render("unit8.Rmd", "html_document")
render("unit9.Rmd", "html_document")
render("unit10.Rmd", "html_document")
